services:
  - type: web
    name: moodmate-backend
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: OTP_EXPIRY_MINUTES
        value: "15"
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_CALLBACK_URL
        sync: false
      - key: PAYSTACK_WEBHOOK_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: JAVA_OPTS
        value: "-XX:MaxRAMPercentage=70"
