import { createClient } from '@supabase/supabase-js';
import * as SecureStore from 'expo-secure-store';

// ─── TODO: Replace these with your real Supabase project values ──────────────
// Dashboard → Project Settings → API
const SUPABASE_URL  = 'https://YOUR_PROJECT_ID.supabase.co';
const SUPABASE_ANON = 'YOUR_ANON_KEY';
// ─────────────────────────────────────────────────────────────────────────────

// expo-secure-store adapter — works in Expo Go, no native module required.
// SecureStore has a 2KB per-key limit; we chunk large values to stay under it.
const CHUNK_SIZE = 1800;

const secureStoreAdapter = {
  getItem: async (key: string): Promise<string | null> => {
    try {
      const count = await SecureStore.getItemAsync(`${key}__chunks`);
      if (count) {
        const n = parseInt(count, 10);
        const parts: string[] = [];
        for (let i = 0; i < n; i++) parts.push((await SecureStore.getItemAsync(`${key}__${i}`)) ?? '');
        return parts.join('');
      }
      return await SecureStore.getItemAsync(key);
    } catch { return null; }
  },
  setItem: async (key: string, value: string): Promise<void> => {
    try {
      if (value.length > CHUNK_SIZE) {
        const n = Math.ceil(value.length / CHUNK_SIZE);
        await SecureStore.setItemAsync(`${key}__chunks`, String(n));
        for (let i = 0; i < n; i++) {
          await SecureStore.setItemAsync(`${key}__${i}`, value.slice(i * CHUNK_SIZE, (i + 1) * CHUNK_SIZE));
        }
      } else {
        await SecureStore.setItemAsync(key, value);
      }
    } catch { /* noop */ }
  },
  removeItem: async (key: string): Promise<void> => {
    try {
      const count = await SecureStore.getItemAsync(`${key}__chunks`);
      if (count) {
        const n = parseInt(count, 10);
        for (let i = 0; i < n; i++) await SecureStore.deleteItemAsync(`${key}__${i}`);
        await SecureStore.deleteItemAsync(`${key}__chunks`);
      } else {
        await SecureStore.deleteItemAsync(key);
      }
    } catch { /* noop */ }
  },
};

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON, {
  auth: {
    // MoodMate uses its own auth backend, not Supabase auth.
    // Disabling persistence and auto-refresh prevents AsyncStorage errors in Expo Go.
    persistSession:     false,
    autoRefreshToken:   false,
    detectSessionInUrl: false,
  },
});

/*
 * ── Supabase SQL setup ────────────────────────────────────────────────────────
 * Run these once in the Supabase SQL editor (Dashboard → SQL Editor):
 *
 * -- 1. Messages table
 * CREATE TABLE IF NOT EXISTS messages (
 *   id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   conversation_id INTEGER      NOT NULL,
 *   sender_id       UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
 *   sender_name     TEXT         NOT NULL,
 *   body            TEXT         NOT NULL,
 *   created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
 * );
 *
 * -- 2. Row-level security (only message participants can read/write)
 * ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
 *
 * CREATE POLICY "Users can insert their own messages"
 *   ON messages FOR INSERT
 *   WITH CHECK (auth.uid() = sender_id);
 *
 * CREATE POLICY "Users can read messages in their conversations"
 *   ON messages FOR SELECT
 *   USING (
 *     conversation_id IN (
 *       SELECT id FROM conversations
 *       WHERE student_id = auth.uid() OR counsellor_id = auth.uid()
 *     )
 *   );
 *
 * -- 3. Enable realtime for the messages table
 * ALTER PUBLICATION supabase_realtime ADD TABLE messages;
 * ─────────────────────────────────────────────────────────────────────────────
 */
